scala_library(
	sources=rglobs('*.scala'),
	dependencies=[
    	'3rdparty/jvm:neo4jJavaDriver',
    	'3rdparty/jvm:circeCore',
    	'3rdparty/jvm:circeGeneric',
    	# '3rdparty/jvm:circeParser',
    	'src/scala/scala4neo/util',
    	'src/scala/scala4neo/model',
  	],
)